
CREATE TABLE recipes (
    recipe_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    recipe_name VARCHAR2(100) NOT NULL,
    ingredients CLOB NOT NULL,
    description CLOB
);

CREATE TABLE preparations (
    step_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    recipe_id NUMBER NOT NULL,
    step_number NUMBER NOT NULL,
    instruction CLOB NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipes(recipe_id) ON DELETE CASCADE
);

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Spaghetti Bolognese', 'spaghetti, ground beef, tomato sauce, onions, garlic', 'A classic Italian pasta dish with a rich meat sauce.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chocolate Chip Cookies', 'flour, sugar, butter, chocolate chips', 'Delicious cookies with melted chocolate chips.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Caesar Salad', 'romaine lettuce, croutons, parmesan cheese, Caesar dressing', 'A fresh salad with crunchy croutons and creamy dressing.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Spaghetti Tounsia', 'spaghetti, potato', 'A Tunisian twist on the traditional spaghetti.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Vegetable Stir Fry', 'carrot, bell pepper, broccoli, soy sauce, garlic, ginger', 'A quick and healthy stir fry with colorful vegetables.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Alfredo', 'chicken breast, heavy cream, garlic, parmesan cheese, fettuccine', 'Creamy pasta with tender chicken and parmesan.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Grilled Cheese Sandwich', 'bread, cheese, butter', 'A warm and comforting sandwich with melted cheese.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Pancakes', 'flour, sugar, eggs, milk, baking powder', 'Fluffy, golden pancakes perfect for breakfast.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Beef Tacos', 'ground beef, taco shells, lettuce, tomato, cheese, sour cream', 'Tasty tacos with seasoned beef and fresh toppings.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Tomato Soup', 'tomatoes, onions, garlic, vegetable broth, basil', 'A hearty, comforting soup made with fresh tomatoes.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Veggie Burger', 'black beans, lentils, breadcrumbs, lettuce, tomato, onion', 'A savory vegetarian burger with black beans and lentils.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Lemon Meringue Pie', 'lemon, sugar, eggs, meringue, pie crust', 'A tangy and sweet lemon pie with a fluffy meringue.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Caesar Wrap', 'chicken breast, romaine lettuce, Caesar dressing, flour tortilla', 'A wrap with chicken, Caesar dressing, and crisp lettuce.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Mushroom Risotto', 'mushrooms, rice, vegetable broth, parmesan cheese, garlic', 'A creamy rice dish with earthy mushrooms and parmesan.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Pulled Pork Sandwich', 'pork shoulder, barbecue sauce, hamburger buns, pickles', 'Slow-cooked pulled pork served on soft buns with pickles.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Apple Pie', 'apples, sugar, flour, cinnamon, pie crust', 'A sweet, spiced pie made with fresh apples.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Stir Fry', 'chicken breast, soy sauce, broccoli, bell pepper, garlic', 'A stir fry with tender chicken and colorful vegetables.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Tuna Salad', 'canned tuna, lettuce, mayo, pickles, onion', 'A refreshing salad with tuna, lettuce, and mayo.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Fried Rice', 'rice, vegetables, soy sauce, garlic, egg', 'A flavorful fried rice dish with veggies and egg.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Beef Stew', 'beef, potatoes, carrots, onions, beef broth', 'A rich beef stew with potatoes and carrots.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Wings', 'chicken wings, garlic, soy sauce, honey, chili flakes', 'Crispy chicken wings with a sweet and spicy glaze.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Salmon Fillet', 'salmon fillet, lemon, garlic, olive oil', 'A simple and delicious salmon fillet with garlic and lemon.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Lasagna', 'ground beef, tomato sauce, lasagna noodles, mozzarella cheese', 'A comforting lasagna with layers of beef and cheese.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Vegetarian Chili', 'beans, tomatoes, onion, garlic, chili powder', 'A hearty chili with beans and a spicy kick.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Meatball Sub', 'ground beef, sub rolls, marinara sauce, mozzarella cheese', 'A sub sandwich with meatballs, marinara, and melted cheese.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Tikka Masala', 'chicken, yogurt, spices, tomato, rice', 'A flavorful Indian chicken dish with yogurt and spices.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Shrimp Scampi', 'shrimp, garlic, butter, lemon, pasta', 'Shrimp cooked with garlic, butter, and lemon served over pasta.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Pork Schnitzel', 'pork, breadcrumbs, eggs, lemon, flour', 'Crispy breaded pork cutlets served with lemon.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('BBQ Ribs', 'pork ribs, barbecue sauce, garlic, brown sugar', 'Tender pork ribs coated in a smoky barbecue sauce.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Chicken Pot Pie', 'chicken, vegetables, pie crust, heavy cream', 'A creamy chicken pie filled with vegetables.');

INSERT INTO recipes (recipe_name, ingredients, description)
VALUES ('Beef Burritos', 'ground beef, tortillas, beans, cheese, salsa', 'Spicy and savory beef burritos with cheese and salsa.');

-- Spaghetti Bolognese
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (1, 1, 'Boil the spaghetti in salted water until al dente.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (1, 2, 'Cook ground beef in a pan until browned.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (1, 3, 'Add tomato sauce, onions, and garlic to the beef and simmer.');

-- Chocolate Chip Cookies
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (2, 1, 'Preheat oven to 180°C (350°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (2, 2, 'Cream together butter, sugar, and eggs.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (2, 3, 'Mix in flour and chocolate chips.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (2, 4, 'Scoop onto a baking tray and bake for 10-12 minutes.');

-- Caesar Salad
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (3, 1, 'Wash and chop romaine lettuce.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (3, 2, 'Prepare Caesar dressing by mixing mayonnaise, lemon juice, and anchovies.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (3, 3, 'Toss lettuce with dressing, croutons, and parmesan cheese.');

-- Spaghetti Tounsia
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (4, 1, 'Boil spaghetti in salted water.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (4, 2, 'Prepare a potato-based sauce with spices.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (4, 3, 'Mix spaghetti with the Tunisian-style sauce.');

-- Vegetable Stir Fry
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (5, 1, 'Chop all vegetables into bite-sized pieces.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (5, 2, 'Heat oil in a wok and add garlic and ginger.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (5, 3, 'Add vegetables and stir fry with soy sauce.');

-- Chicken Alfredo
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (6, 1, 'Cook fettuccine pasta until al dente.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (6, 2, 'Sauté chicken breast pieces until golden.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (6, 3, 'Prepare a creamy sauce with heavy cream and parmesan.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (6, 4, 'Mix pasta, chicken, and sauce together.');

-- Grilled Cheese Sandwich
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (7, 1, 'Butter one side of each slice of bread.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (7, 2, 'Place cheese between two slices of bread.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (7, 3, 'Toast the sandwich on a skillet until golden brown.');

-- Pancakes
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (8, 1, 'Mix flour, sugar, baking powder, and milk into a batter.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (8, 2, 'Heat a skillet and pour the batter into rounds.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (8, 3, 'Cook until bubbles form, then flip.');

-- Beef Tacos
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (9, 1, 'Cook ground beef with taco seasoning.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (9, 2, 'Warm taco shells and fill with beef.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (9, 3, 'Add lettuce, tomato, cheese, and sour cream.');

-- Tomato Soup
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (10, 1, 'Sauté onions and garlic in a pot.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (10, 2, 'Add tomatoes and vegetable broth, then simmer.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (10, 3, 'Blend the soup until smooth.');


-- Veggie Burger
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (11, 1, 'Mash black beans and lentils together.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (11, 2, 'Mix with breadcrumbs, onion, and spices.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (11, 3, 'Form into patties and cook in a pan.');

-- Lemon Meringue Pie
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (12, 1, 'Preheat the oven to 180°C (350°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (12, 2, 'Mix lemon juice, sugar, and eggs for the filling.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (12, 3, 'Pour into the pie crust and bake for 25 minutes.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (12, 4, 'Top with meringue and bake for another 10 minutes.');

-- Chicken Caesar Wrap
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (13, 1, 'Cook chicken breast and slice it.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (13, 2, 'Toss lettuce with Caesar dressing.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (13, 3, 'Place chicken and dressing in a tortilla and wrap.');

-- Mushroom Risotto
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (14, 1, 'Sauté mushrooms and garlic in a pan.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (14, 2, 'Add rice and vegetable broth, stirring frequently.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (14, 3, 'Cook until rice is tender, then stir in parmesan cheese.');

-- Pulled Pork Sandwich
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (15, 1, 'Cook pork shoulder in a slow cooker with barbecue sauce.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (15, 2, 'Shred the pork once cooked.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (15, 3, 'Serve on hamburger buns with pickles.');

-- Apple Pie
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (16, 1, 'Preheat the oven to 220°C (425°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (16, 2, 'Mix apples, sugar, cinnamon, and flour.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (16, 3, 'Fill the pie crust with apple mixture and bake for 45 minutes.');

-- Chicken Stir Fry
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (17, 1, 'Sauté chicken breast pieces in oil.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (17, 2, 'Add broccoli and bell pepper.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (17, 3, 'Stir in soy sauce and cook until vegetables are tender.');

-- Tuna Salad
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (18, 1, 'Mix canned tuna with mayo, chopped pickles, and onions.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (18, 2, 'Serve over lettuce or on a sandwich.');

-- Fried Rice
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (19, 1, 'Cook rice and set aside.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (19, 2, 'Sauté vegetables and garlic in oil.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (19, 3, 'Add rice and soy sauce, then scramble in an egg.');

-- Beef Stew
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (20, 1, 'Brown beef chunks in a large pot.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (20, 2, 'Add potatoes, carrots, onions, and beef broth.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (20, 3, 'Simmer until beef and vegetables are tender.');

-- Chicken Wings
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (21, 1, 'Preheat the oven to 200°C (400°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (21, 2, 'Toss chicken wings in soy sauce, garlic, and honey.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (21, 3, 'Bake for 25-30 minutes until crispy.');

-- Salmon Fillet
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (22, 1, 'Preheat oven to 180°C (350°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (22, 2, 'Season salmon fillet with garlic, lemon, and olive oil.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (22, 3, 'Bake for 15-20 minutes until flaky.');

-- Lasagna
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (23, 1, 'Cook lasagna noodles according to package instructions.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (23, 2, 'Layer beef, tomato sauce, noodles, and mozzarella in a baking dish.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (23, 3, 'Bake for 45 minutes at 180°C (350°F).');

-- Vegetarian Chili
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (24, 1, 'Sauté onions and garlic in a pot.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (24, 2, 'Add beans, tomatoes, chili powder, and vegetable broth.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (24, 3, 'Simmer for 30 minutes, then serve.');

-- Meatball Sub
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (25, 1, 'Mix ground beef, breadcrumbs, and marinara sauce to form meatballs.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (25, 2, 'Bake meatballs at 180°C (350°F) for 20 minutes.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (25, 3, 'Place meatballs in sub rolls, top with marinara and mozzarella, and bake for 5 minutes.');

-- Chicken Tikka Masala
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (26, 1, 'Marinate chicken in yogurt and spices for 1 hour.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (26, 2, 'Cook chicken in a pan until browned.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (26, 3, 'Add tomato sauce and simmer for 20 minutes.');

-- Shrimp Scampi
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (27, 1, 'Cook pasta according to package instructions.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (27, 2, 'Sauté shrimp with garlic and butter.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (27, 3, 'Toss shrimp and garlic butter with pasta, adding lemon juice.');

-- Pork Schnitzel
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (28, 1, 'Dredge pork cutlets in flour, egg, and breadcrumbs.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (28, 2, 'Fry the schnitzels in hot oil until golden.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (28, 3, 'Serve with lemon wedges.');

-- BBQ Ribs
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (29, 1, 'Preheat grill to medium heat.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (29, 2, 'Brush ribs with barbecue sauce.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (29, 3, 'Grill ribs for 30 minutes, basting with more sauce.');

-- Chicken Pot Pie
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (30, 1, 'Preheat oven to 180°C (350°F).');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (30, 2, 'Cook chicken and vegetables in a pan.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (30, 3, 'Add heavy cream, mix with pie crust, and bake for 30 minutes.');

-- Beef Burritos
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (31, 1, 'Cook ground beef with taco seasoning.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (31, 2, 'Warm tortillas and fill with beef, beans, and cheese.');
INSERT INTO preparations (recipe_id, step_number, instruction)
VALUES (31, 3, 'Roll up the tortillas and serve with salsa.');




